/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuotationsRouteImport } from './routes/quotations'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as FollowupsRouteImport } from './routes/followups'
import { Route as IndexRouteImport } from './routes/index'

const QuotationsRoute = QuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowupsRoute = FollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/followups': typeof FollowupsRoute
  '/leads': typeof LeadsRoute
  '/pipeline': typeof PipelineRoute
  '/quotations': typeof QuotationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/followups': typeof FollowupsRoute
  '/leads': typeof LeadsRoute
  '/pipeline': typeof PipelineRoute
  '/quotations': typeof QuotationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/followups': typeof FollowupsRoute
  '/leads': typeof LeadsRoute
  '/pipeline': typeof PipelineRoute
  '/quotations': typeof QuotationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/followups' | '/leads' | '/pipeline' | '/quotations'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/followups' | '/leads' | '/pipeline' | '/quotations'
  id: '__root__' | '/' | '/followups' | '/leads' | '/pipeline' | '/quotations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FollowupsRoute: typeof FollowupsRoute
  LeadsRoute: typeof LeadsRoute
  PipelineRoute: typeof PipelineRoute
  QuotationsRoute: typeof QuotationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quotations': {
      id: '/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followups': {
      id: '/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof FollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FollowupsRoute: FollowupsRoute,
  LeadsRoute: LeadsRoute,
  PipelineRoute: PipelineRoute,
  QuotationsRoute: QuotationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
